services:
  backend:
    build:
      context: ./backend
    container_name: crm-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: crm-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: